2022-10-07 06:58:17,861 INFO    MainThread:23088 [wandb_setup.py:_flush():68] Configure stats pid to 23088
2022-10-07 06:58:17,861 INFO    MainThread:23088 [wandb_setup.py:_flush():68] Loading settings from /data1/home/chxy/.config/wandb/settings
2022-10-07 06:58:17,861 INFO    MainThread:23088 [wandb_setup.py:_flush():68] Loading settings from /data1/home/chxy/tag推荐/cxy_tag_new/wandb/settings
2022-10-07 06:58:17,861 INFO    MainThread:23088 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2022-10-07 06:58:17,861 INFO    MainThread:23088 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program_relpath': 'main.py', 'program': '/data1/home/chxy/tag推荐/cxy_tag_new/main.py'}
2022-10-07 06:58:17,862 INFO    MainThread:23088 [wandb_init.py:_log_setup():476] Logging user logs to /data1/home/chxy/tag推荐/cxy_tag_new/wandb/run-20221007_065817-2fvqfnuj/logs/debug.log
2022-10-07 06:58:17,862 INFO    MainThread:23088 [wandb_init.py:_log_setup():477] Logging internal logs to /data1/home/chxy/tag推荐/cxy_tag_new/wandb/run-20221007_065817-2fvqfnuj/logs/debug-internal.log
2022-10-07 06:58:17,862 INFO    MainThread:23088 [wandb_init.py:init():516] calling init triggers
2022-10-07 06:58:17,862 INFO    MainThread:23088 [wandb_init.py:init():520] wandb.init called with sweep_config: {}
config: {}
2022-10-07 06:58:17,862 INFO    MainThread:23088 [wandb_init.py:init():569] starting backend
2022-10-07 06:58:17,862 INFO    MainThread:23088 [wandb_init.py:init():573] setting up manager
2022-10-07 06:58:17,872 INFO    MainThread:23088 [backend.py:_multiprocessing_setup():104] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-10-07 06:58:17,880 INFO    MainThread:23088 [wandb_init.py:init():580] backend started and connected
2022-10-07 06:58:17,891 INFO    MainThread:23088 [wandb_init.py:init():658] updated telemetry
2022-10-07 06:58:17,892 INFO    MainThread:23088 [wandb_init.py:init():694] communicating run to backend with 60 second timeout
2022-10-07 06:58:20,949 WARNING MsgRouterThr:23088 [router.py:message_loop():77] message_loop has been closed
2022-10-07 06:58:27,906 ERROR   MainThread:23088 [wandb_init.py:init():1105] error
Traceback (most recent call last):
  File "/data1/home/chxy/anaconda3/envs/pytorch1.3/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 1078, in init
    run = wi.init()
  File "/data1/home/chxy/anaconda3/envs/pytorch1.3/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 698, in init
    timeout=self.settings.init_timeout, on_progress=self._on_progress_init
  File "/data1/home/chxy/anaconda3/envs/pytorch1.3/lib/python3.7/site-packages/wandb/sdk/lib/mailbox.py", line 259, in wait
    raise MailboxError("transport failed")
wandb.errors.MailboxError: transport failed
